CREATE TABLE faq (
  HEADER_ID INT PRIMARY KEY,
  QUES_TYPE_CN VARCHAR(255),
  QUES_TYPE_EN VARCHAR(255),
  QUESTION_CN TEXT,
  QUESTION_EN TEXT,
  ANSWER_CN TEXT,
  ANSWER_EN TEXT,
  CREATE_USER VARCHAR(100) DEFAULT NULL,
  CREATE_DATE DATETIME,
  LAST_UPDATE_USER VARCHAR(100) DEFAULT NULL,
  LAST_UPDATE_DATE DATETIME,
  ROWID VARCHAR(50)
);


INSERT INTO faq (
  HEADER_ID, QUES_TYPE_CN, QUES_TYPE_EN, QUESTION_CN, QUESTION_EN,
  ANSWER_CN, ANSWER_EN, CREATE_USER, CREATE_DATE, LAST_UPDATE_USER,
  LAST_UPDATE_DATE, ROWID
) VALUES
(
  1,
  '修改工人薪金/強積金戶口資料',
  'Modify Worker’s Salary / Mandatory Provident Fund Account Information',
  '當我點擊儲存按鈕後，銀行帳號/強積金計畫號碼的輸入欄會顯示為紅色和紫色。 這些顏色代表什麼？',
  'After I clicks the save button, the input filed of bank account numbers/MPF scheme number appears to be colored in red and purple. What does these color indicate?',
  '紅色為員工戶口號碼／計劃成員編號輸入上出錯。\n紫色為員工戶口號碼／計劃成員編號已存在。',
  'Red indicates an error in the input of bank account number / MPF scheme number.\nPurple indicates that the bank account number / MPF scheme number already exists.',
  NULL,
  '2025-09-10 08:49:10',
  NULL,
  '2025-09-10 08:49:10',
  'AAAfdTAC9AABoC+AAA'
),
(
  2,
  '輸入/修改工人薪金/強積金資料',
  'Enter/Edit Worker Salary/MPF Information',
  '如何列印一份完整的員工薪金／強積金資料副本？',
  'How can I print a complete copy of an employee\'s salary/MPF data?',
  '如需列印完整副本，可以先按「核對」按鈕，將其匯出為Excel檔案，再進行列印。',
  'To print a complete copy, you can verify the data and export it as an Excel file for printing.',
  NULL,
  '2025-09-10 08:49:10',
  NULL,
  '2025-09-10 08:49:10',
  'AAAfdTAC9AABoC+AAC'
),
(
  3,
  '輸入/修改工人薪金/強積金資料',
  'Enter/Edit Worker Salary/MPF Information',
  '如果工人有加班，應該如何記錄？',
  'What should I do if an employee has overtime?',
  '您可以增加工人的「每日入息」金額來計算加班費用。',
  'You can increase the "daily income" amount to account for overtime.',
  NULL,
  '2025-09-10 08:49:10',
  NULL,
  '2025-09-10 08:49:10',
  'AAAfdTAC9AABoC+AAD'
),
(
  4,
  '輸入/修改工人薪金/強積金資料',
  'Enter/Edit Worker Salary/MPF Information',
  '如果工人暫時沒有銀行帳號，但有強積金號碼，是否要填寫強積金號碼？如果不填寫銀行帳號，而是以現金支付薪資，如何處理強積金？',
  'If an employee temporarily doesn\'t have a bank account number but has an MPF number, should I fill in the MPF number? How should I handle MPF if the bank account number is not provided and the payment is made in cash?',
  '工人必須同時擁有銀行帳號和強積金號碼。公司鼓勵使用系統進行薪資發放，並獎勵強積金的繳納。如果銀行帳號和強積金號碼未填寫，請在備註欄中填寫「未有銀行帳號/強積金號碼」以確保薪資計算的準確性。',
  'It is not allowed to have an MPF number without a bank account. The company encourages using the system to process payments, which will reward MPF contributions. If the bank account and MPF numbers are missing, you can input a remark "No bank account/MPF number" to ensure the calculation of wages.',
  NULL,
  '2025-09-10 08:49:10',
  NULL,
  '2025-09-10 08:49:10',
  'AAAfdTAC9AABoC+AAE'
),
(
  5,
  '輸入/修改工人薪金/強積金資料',
  'Enter/Edit Worker Salary/MPF Information',
  '若工人只上半天班，該如何填寫？',
  'How should I fill in the information for an employee who works half a day?',
  '您可以手動將「每日入息」金額除以2。',
  'You can manually divide the "daily income" amount by 2.',
  NULL,
  '2025-09-10 08:49:10',
  NULL,
  '2025-09-10 08:49:10',
  'AAAfdTAC9AABoC+AAF'
),
(
  6,
  '輸入/修改工人薪金/強積金資料',
  'Enter/Edit Worker Salary/MPF Information',
  '我已在備註中註明，但系統仍顯示「沒有員工銀行帳號」。我該怎麼辦？',
  'I have already indicated in the remarks, but the system still shows "No employee bank account number". What should I do?',
  '如果未填寫銀行帳號，則無法支付薪資。如果工人希望以支票或其他方式收取工資，則只需填寫備註，否則不需要填寫任何資訊。',
  'If the bank account number is not filled in, the wages cannot be paid. If the employee intends to receive payment via check or other means, only the remarks need to be filled in. Otherwise, no information should be entered.',
  NULL,
  '2025-09-10 08:49:10',
  NULL,
  '2025-09-10 08:49:10',
  'AAAfdTAC9AABoC+AAG'
),
(
  7,
  '輸入/修改工人薪金/強積金資料',
  'Enter/Edit Worker Salary/MPF Information',
  '如果系統顯示「實際工作天數為零，每日收入不能大於零」，針對沒有出勤記錄的工人，該怎麼辦？',
  'If the system shows "actual working days are zero, daily income cannot be greater than zero" for employees who have no attendance records, what should I do?',
  '不要填寫任何收入金額，並在備註中註明「不出糧」。',
  'Do not enter any income and write a remark stating "No payment."',
  NULL,
  '2025-09-10 08:49:10',
  NULL,
  '2025-09-10 08:49:10',
  'AAAfdTAC9AABoC+AAH'
),
(
  8,
  '工人出入記錄一覽表',
  'List of worker entry and exit records',
  '員工出勤紀錄表中的強積金為何會出現小數點？',
  'Why are there decimal points in the MPF records on the employee attendance summary?',
  '當員工在同一天在多個工地工作時，薪資和強積金會依照各工地的百分比進行拆分。例如，如果員工在一個工地工作，分配金額為50元；在兩個工地工作，則分配金額為25元；在三個工地工作，則分配金額為16.67元。當所有工地的強積金合計時，總金額應為50元。',
  'When an employee works at multiple construction sites on the same day, the salary and MPF contributions are divided based on the percentage allocated to each site. For example, if a $50 employee worked at one site, $25 is allocated for working at two sites, and $16.67 is allocated for working at three sites. When you add up the MPF contributions from all sites, the total amount will be $50.',
  NULL,
  '2025-09-10 08:49:10',
  NULL,
  '2025-09-10 08:49:10',
  'AAAfdTAC9AABoC+AAI'
),
(
  9,
  '查詢已製作自動轉賬檔案之糧期表',
  'Check the payroll periods with generated automatic transfer files',
  '香港特別行政區政府的強積金指引',
  'The MPF guidelines of the HKSAR',
  '僱主及僱員每日須強制繳交的供款額會因僱員的每日有關入息而不同。若每日收入少於 280 元，僱主須供款 10 元，而僱員毋須供款。若每日收入介乎 280 至不足 350 元，僱主及僱員各須供款 15 元。若每日收入介乎 350 至不足 450 元，僱主及僱員各須供款 20 元。若每日收入介乎 450 至不足 550 元，僱主及僱員各須供款 25 元。若每日收入介乎550 至不足 650 元，僱主及僱員各須供款 30 元。若每日收入介乎 650 至不足 750 元，僱主及僱員各須供款 35 元。若每日收入介乎,',
  'The mandatory daily contribution amounts for employers and employees vary according to the employee’s relevant daily income.- If the daily income is less than $280, the employer must contribute $10, and the employee is not required to contribute. If the daily income is between $280 and less than $350, both the employer and the employee must each contribute $15. If the daily income is between $350 and less than $450, both must each contribute $20. If the daily income is between $450 and less than $550, both must each contribute $25. If the daily income is between $550 and less than $650, both must each contribute $30.If the daily income is between $650 and less than $750, both must each contribute $35.If the daily income is between $750 and less than $850, both must each contribute $40.If the daily income is between $850 and less than $950, both must each contribute $45.Finally, if the daily income is $950 or above, the contribution amount reaches the maximum limit, and both the employer and the employee must each make a mandatory contribution of $50.',
  NULL,
  '2025-09-10 08:49:10',
  NULL,
  '2025-09-10 08:49:10',
  'AAAfdTAC9AABoC+AAJ'
),
(
  10,
  '製作自動轉賬檔案',
  'Generate an automatic transfer file',
  '「製作自動轉賬檔案」頁面中為何沒有任何選項?',
  'Why are there no options available in "Auto Transfer Of Workers\' Salary/MPF" page?',
  '請前往「工人薪金/強積金自動轉賬」，在流程圖中選擇適當的選項，即「完成整個糧期」或「分配短糧期」或「分配部分糧期」。',
  'Please go to "Auto Transfer Of Workers\' Salary/MPF" page and select the appropriate option in the flow chart, i.e. "Complete The Entire Payroll Period" or "Allocate Short Pay Period" or "Allocation Of Partial Payroll".',
  NULL,
  '2025-09-10 08:49:10',
  NULL,
  '2025-09-10 08:49:10',
  'AAAfdTAC9AABoC/AAA'
),
(
  11,
  '輸入/修改工人薪金/強積金資料',
  'Enter/Edit Worker Salary/MPF Information',
  '工人薪資調整後，每天入息資料出錯了，應該怎麼辦？',
  'What should I do if the workers\' daily income information is incorrect after a salary adjustment?',
  '跟發卡中心發卡中心聯絡，更新工人每天入息。',
  'Contact the card center to update the workers\' daily income.',
  NULL,
  '2025-09-10 08:49:11',
  NULL,
  '2025-09-10 08:49:11',
  'AAAfdTAC9AABoC/AAB'
),
(
  12,
  '製作自動轉賬檔案',
  'Generate an automatic transfer file',
  '沒填銀行帳號和強積金號碼，但填寫了備注，導致制作糧期表失敗，應該怎麼辦？',
  'What should I do if the payroll schedule creation failed because the bank account number and MPF scheme member number were not filled in, but the remarks were provided?',
  '填寫了每日入息就一定要填寫「銀行號號」和「強積金計劃成員編號」。',
  'When filling in the daily income, it is mandatory to provide the "bank account number" and "MPF scheme number."',
  NULL,
  '2025-09-10 08:49:11',
  NULL,
  '2025-09-10 08:49:11',
  'AAAfdTAC9AABoC/AAC'
),
(
  13,
  '輸入/修改工人薪金/強積金資料',
  'Enter/Edit Worker Salary/MPF Information',
  '「完成整個糧期」、「分配短糧期」及「分配部分糧期」之間有何不同？',
  'What are the differences between "Complete Payroll Period," "Short Payroll Period Allocation," and "Partial Payroll Period Allocation"?',
  '「完成整個糧期」－在一般情況下．承判商都會一次過為所有工人出糧。 「完成整個糧期」最適合大部份承判商使用。\n\n「分配短糧期」－如需要將一個大糧期分割成多個短糧期，並按每個短糧期出糧，可以採用「分配短期」。\n\n「分配部份糧期」－如需要將一班工人在一個糧期內先後出糧，可以採用「分配部分糧期」 。',
  'Complete Wage Period - In general, contractors will pay all workers at once. "Complete Wage Period" is suitable for most contractors.\n\nAllocate Short Wage Periods - If you need to split a large wage period into several shorter wage periods and pay wages according to each short wage period, you can use "Allocate Short Wage Periods."\n\nAllocate Partial Wage Periods - If you need to pay a group of workers at different times within a single wage period, you can use "Allocate Partial Wage Periods."',
  NULL,
  '2025-09-10 08:49:11',
  NULL,
  '2025-09-10 08:49:11',
  'AAAfdTAC9AABoC/AAD'
),
(
  14,
  '輸入/修改工人薪金/強積金資料',
  'Enter/Edit Worker Salary/MPF Information',
  '工人出入閘記錄不全，例如只有入閘打卡記錄，出閘時忘記打卡。導致員工未有顯示在「輸入或修改工人薪金/強積金資料」頁面，應該怎麼辦？',
  'The records of workers\' entry and exit are incomplete. For example, there are instances where only the entry punch is recorded, but the exit punch is forgotten. As a result, employees are not displayed on the "Input or Modify Workers\' Salary or MPF Inform',
  '如果需要為該工人入數，請聯絡我們，我們需要幫他設定數據進入薪金員工表，工人才能顯示在「輸入或修改工人薪金/強積金資料」頁面中。',
  'If you need assistance with entering the data, please contact us. We need to manually enter the data into the payroll employee table so that the worker can be displayed on the "Input or Modify Workers\' Salary/MPF Information" page.',
  NULL,
  '2025-09-10 08:49:11',
  NULL,
  '2025-09-10 08:49:11',
  'AAAfdTAC9AABoC/AAE'
),
(
  15,
  '使用者驗證',
  'User Authentication',
  '更改/重設密碼',
  'Change password / Reset password',
  '步驟一，登入系統。\n步驟二，按網頁右上角的按鈕後按更改密碼。\n步驟三，輸入現行使用的密碼及兩次新密碼後按 Save。\n\n用戶密碼必須符合以下要求：\n1. 最少8個位，最多10個位。\n2. 以字母開頭，並包含至少1個數字和1個大寫字母。\n3. 用戶必須每六個月至少更換一次密碼，對上三次使用過的密碼不能重複使用。',
  'Step 1: Log in to the Vendor Portal.\nStep 2: Click the button at the top right corner of the webpage, then press “Change Password”.\nStep 3: Enter your current password, then enter the new password twice, and click Save.\nPassword requirements:\n- Must be at least 8 characters and no more than 10 characters.\n- Must begin with a letter and include at least one number and one uppercase letter.\n- You must change your password at least once every six months, and you cannot reuse any of your last three passwords.',
  NULL,
  '2025-09-10 08:49:11',
  NULL,
  '2025-09-10 08:49:11',
  'AAAfdTAC9AABoC/AAF'
),
(
  16,
  '使用者驗證',
  'User Authentication',
  '忘記密碼',
  'Forget password　',
  '步驟一：於登入頁面點選 「Change or Reset Password」 以更改密碼。\n步驟二：輸入相關資料，包括帳號及已於本通信網登記的電郵地址。\n步驟三：點選 「Get Code」 後，前往電郵信箱查收並讀取認證碼。\n步驟四：輸入認證碼完成驗證。',
  'Step 1: On the login page, click “Change or Reset Password” to change your password.\nStep 2: Enter the required information, including your account and the email address registered.\nStep 3: Click “Get Code”, then check your email inbox to retrieve the verification code.\nStep 4: Enter the verification code to complete the verification process.',
  NULL,
  '2025-09-10 08:49:11',
  NULL,
  '2025-09-10 08:49:11',
  'AAAfdTAC9AABoC/AAG'
);


INSERT INTO `faq` (`HEADER_ID`, `QUES_TYPE_CN`, `QUES_TYPE_EN`, `QUESTION_CN`, `QUESTION_EN`, `ANSWER_CN`, `ANSWER_EN`, `CREATE_USER`, `CREATE_DATE`, `LAST_UPDATE_USER`, `LAST_UPDATE_DATE`, `ROWID`) VALUES
('17', 'Tender', '投標標書', '為什麼我無法提交標書？', 'Why can''t I submit the tender?', '請確認是否已完成所有報價項目填寫、選擇「包括／不包括」、列印並上載投標表格。', 'Please confirm that all quotation items have been filled in, select "Include/Exclude", print and upload the tender form.', 'Lucas', NOW(), 'Lucas', NOW(), NULL),
('18', 'Tender', '投標標書', '標書編號以 ST 開頭是什麼類型的標書？', 'What type of tender is indicated by a tender number starting with "ST"?', 'ST開頭代表地盤快標，包含填寫報價單與提交標書兩個步驟。', 'A tender number starting with ST represents a Site Fast Tender, which involves filling in the quotation form and submitting the tender.', 'Lucas', NOW(), 'Lucas', NOW(), NULL),
('19', 'Tender', '投標標書', '標書編號以數字開頭是什麼類型的標書？', 'What type of tender is indicated by a tender number that begins with a digit?', '數字開頭代表合約發判組標書，包含填寫報價單、列印投標表格與提交標書。', 'A tender number starting with a digit indicates a Contract Award Tender, which includes filling in the quotation form, printing the Form of Tender, and submitting the tender.', 'Lucas', NOW(), 'Lucas', NOW(), NULL),
('20', 'Tender', '投標標書', '標書編號以 P 開頭是什麼類型的標書？', 'What type of tender is represented by a tender number starting with "P"?', 'P開頭代表購料組標書，包含填寫報價單、列印投標表格與提交標書。您可在網頁報價單中新增替代項目，但 BQ Excel 不支援新增。', 'A tender number starting with P refers to a Procurement Tender, which requires filling in the quotation form, printing the Form of Tender, and submitting the tender. Alternative items can be added via the web quotation form, but BQ Excel does not support item addition.', 'Lucas', NOW(), 'Lucas', NOW(), NULL),
('21', 'Tender', '投標標書', '標書編號以 LS 開頭是什麼類型的標書？', 'What type of tender does a tender number beginning with "LS" refer to?', 'LS開頭代表園藝組標書，包含填寫報價單、列印投標表格與提交標書。', 'A tender number starting with LS signifies a Landscaping Tender, which includes filling in the quotation form, printing the Form of Tender, and submitting the tender.', 'Lucas', NOW(), 'Lucas', NOW(), NULL),
('22', 'Tender', '投標標書', '標書編號以 M 開頭是什麼類型的標書？', 'What type of tender is associated with a tender number starting with "M"?', 'M開頭代表維修組標書，包含填寫報價單、列印投標表格與提交標書。', 'A tender number starting with M denotes a Maintenance Tender, which involves filling in the quotation form, printing the Form of Tender, and submitting the tender.', 'Lucas', NOW(), 'Lucas', NOW(), NULL),
('23', 'Tender', '投標標書', '如何填寫報價單？', 'How do I fill in the quotation form?', '本系統有兩種填寫報價單的方法：1. 導出 BQ Excel 在閣下的電腦填寫Excel, 完成後導入BQ Excel。2. 在網頁報價單上直接輸入。 我們建議使用 BQ Excel 填寫報價單，該Excel 是一個備份。萬一發生問題導致資料遺失，導入BQ Excel 可以在 5 秒內補回報價單資料。', 'The system provides two methods for completing the quotation form: 1. Export the BQ Excel file, fill it out on your computer, and then import it back into the system. 2. Enter the data directly into the web-based quotation form. We recommend using the BQ Excel file as your primary method. It serves as a backup, and in case of any issues or data loss, re-importing the Excel file can restore your quotation within 5 seconds.', 'Lucas', NOW(), 'Lucas', NOW(), NULL),
('24', 'Tender', '投標標書', '如何列印投標表格？', 'How do I print the Form of Tender?', '本系統在列印前會對報價單進行檢查。如通過檢查，閣下的電腦會自動下載一份投標表格文件，文件上有貴公司的名稱及標書總價。請核對標書總價是否正確。如沒有問題就可以列印文件並在上方簽署及蓋上公司印章，最後掃描到電腦為 PDF 文件即可上載到「上載投標表格」。如沒有文件下載，請留意一下畫面上有沒有信息提示。如有信息提示，請輸入信息內容。', 'Before printing, the system will verify the contents of the quotation form. If the check is successful, your computer will automatically download the Form of Tender, which includes your company name and the total tender amount. Please confirm that the total amount is correct. If everything is in order, you may print the document, sign and stamp it at the top, then scan it as a PDF file and upload it to the "Upload Tender Form" section. If the file does not download, please check whether any message appears on the screen. If a message is shown, please enter the relevant information as instructed.', 'Lucas', NOW(), 'Lucas', NOW(), NULL),
('25', 'Tender', '投標標書', '如何提交標書？', 'How do I submit the tender?', '本系統規定承判商必須上載本公司認可格式的投標表格文件，才允許承判商操作提交按鈕。如不能按提交按鈕, 請檢查以下事項︰ 1. 必須曾列印投標表格。 2. 在單價為 HK$0 的項目選擇「包括」或「不包括」。 3. 必須填寫全部填價單內容，不能留空。 4. 若回標金額大於HK$10,000,000.00。請須於回標時簽署財務能力承諾書。 5) 上載投標表格後不需要按保存，按遞交完成。如在上載後再次按保存按鈕，本系統會當作標書有修改，必須再次列印投標表格確保文件上的標書總價是最新。', 'The system requires contractors to upload a Form of Tender in the company-approved format before the "Submit" button becomes active. If the "Submit" button cannot be clicked, please check the following: 1. The Form of Tender must have been printed. 2. For items with a unit price of HK$0, you must select either "Included" or "Excluded". 3. All quotation fields must be completed—no fields should be left blank. 4. If the total tender amount exceeds HK$10,000,000.00, a Financial Capability Undertaking must be signed at the time of submission. 5. After uploading the Form of Tender, do not click "Save" again—just click "Submit" to complete the process. If "Save" is clicked after uploading, the system will treat the tender as modified, and you must reprint the Form of Tender to ensure the total amount is up to date.', 'Lucas', NOW(), 'Lucas', NOW(), NULL),
('26', 'Tender', '投標標書', '為什麼「提交標書」按鈕無法點擊或呈灰色狀態？', 'Why is the "Submit Tender" button unclickable or greyed out?', '請留意貴公司是否把已簽署及蓋上公司印章的投標表格 PDF，文件上載到 「上載投標表格」。', 'Please ensure that your company has uploaded the signed and stamped PDF version of the Form of Tender to the "Upload Tender Form" section.', 'Lucas', NOW(), 'Lucas', NOW(), NULL),
('27', 'Tender', '投標標書', '為什麼系統沒有顯示任何警告或提示訊息？', 'Why doesn''t the system display any warning or error message?', '請留意是否因貴公司的瀏覽器已封鎖彈出式視窗，建議把本網站 vendor.sanfield.com.hk 加到白名單或允許本網站的彈出式視窗。', 'Please check whether your browser is blocking pop-up windows. We recommend adding vendor.sanfield.com.hk to your browser’s whitelist or allowing pop-ups from this site.', 'Lucas', NOW(), 'Lucas', NOW(), NULL),
('28', 'Tender', '投標標書', '為什麼我無法取得報價單的 Excel 檔案？', 'Why am I unable to access the Excel file for the quotation?', '請留意是否因貴公司的防毒軟件或防火牆誤把公式當作病毒阻擋了文件下載，建議把本網站 vendor.sanfield.com.hk 加到白名單或允許本網站的彈出式視窗。', 'Please check whether your company''s antivirus software or firewall has mistakenly flagged the formulas in the BQ Excel file as a threat, which may have blocked the download. We recommend adding vendor.sanfield.com.hk to your whitelist or allowing pop-ups from this site.', 'Lucas', NOW(), 'Lucas', NOW(), NULL),
('29', 'Tender', '投標標書', '為什麼系統顯示文件已損壞，無法開啟？', 'Why does the system show that the file is corrupted and cannot be opened?', '請留意該文件如果是從「標書」功能下載的請聯絡標書負責人。「標書」功能內的附件是由標書負責人上載的。', 'Please note that if the file was downloaded from the "Tender" section, you should contact the tender coordinator. Attachments within the "Tender" section are uploaded by the designated tender coordinator.', 'Lucas', NOW(), 'Lucas', NOW(), NULL),
('30', 'Tender', '投標標書', '若我不打算報其中一個報價項目，應如何處理？', 'If I don''t intend to quote for a particular item, how should I handle it?', '本系統提供兩種填寫報價單的方法。第一種方式是將 BQ Excel 匯出至您的電腦進行填寫，完成後再匯入系統。若採用此方式，請在欲報價的項目中輸入「0」，並於成功匯入後，在網頁報價單中選擇該項目的「包括」或「不包括」選項。第二種方式則是直接在網頁報價單上輸入資料，並於每個項目中選擇「包括」或「不包括」，以完成報價設定。', 'The system offers two methods for completing the quotation form. The first method is to export the BQ Excel file to your computer, fill it in, and then import it back into the system. For items you wish to quote, enter “0” if applicable, and after a successful import, select “Included” or “Excluded” for each item in the web quotation form. The second method is to input the data directly into the web quotation form and select “Included” or “Excluded” for each item to complete the quotation setup.', 'Lucas', NOW(), 'Lucas', NOW(), NULL),
('31', 'Tender', '投標標書', '該項目我無法供應，請問應如何處理？', 'If I''m unable to supply a specific item, what should I do?', '如對報價單內容有任何疑問，請聯絡標書負責人。', 'If you have any questions regarding the contents of the quotation form, please contact the tender coordinator.', 'Lucas', NOW(), 'Lucas', NOW(), NULL),
('32', 'Tender', '投標標書', '請問該項目的具體內容或要求是什麼？', 'What are the detailed specifications or requirements for this item?', '如對報價單內容有任何疑問，請聯絡標書負責人。', 'If you have any questions regarding the contents of the quotation form, please contact the tender coordinator.', 'Lucas', NOW(), 'Lucas', NOW(), NULL),
('33', 'Tender', '投標標書', '若我能提供其他品牌的產品，是否可以替代原指定品牌？應如何提交相關資料？', 'If I can offer a product from a different brand, can it be used as a substitute for the specified brand? How should I submit the relevant information?', '如標書是 P 開頭的標書代表購料組標書。你可以在網頁報價單上該報價單項目的最右邊使用 Add Alternative 功能，填寫項目的名稱、單位及單價即可，或在網頁報價單最下方按 Add Item。請注意，BQ Excel 僅限填寫標書中原有的報價項目，系統不支援新增任何項目內容。如果是其他部門的標書，你可以上載一些有關額外報價項目的詳細內容到上載附件就可，標書負責人會再跟您聯絡。', 'For tenders starting with "P", this indicates a Procurement Division tender. You may use the "Add Alternative" function on the far right of the relevant item in the web quotation form to enter the item name, unit, and unit rate. Alternatively, you can click "Add Item" at the bottom of the web quotation form. Please note that BQ Excel is limited to filling in the original quotation items listed in the tender. The system does not support adding new items via Excel. For tenders from other departments, you may upload detailed information regarding additional quotation items under "Upload Attachments". The tender coordinator will follow up with you accordingly.', 'Lucas', NOW(), 'Lucas', NOW(), NULL),
('34', 'Tender', '投標標書', '為什麼在按下「列印投標表格」時，系統顯示「必須輸入單價或數量」的提示訊息？', 'Why does the system display the message “The Unit Price or Quantity cannot be empty”?', '請確保所有報價單項目均已填寫，欄位不得留空。請於網頁報價單中尋找紅色標示的項目，並完成填寫後再提交。', 'Please ensure all quotation items are fully completed. Fields must not be left blank. Check the web quotation form for any items marked in red, fill them in, and then proceed with submission.', 'Lucas', NOW(), 'Lucas', NOW(), NULL),
('35', 'Tender', '投標標書', '為什麼系統顯示「單價不能為 0」？', 'Why does the system display the error message “Please choose ‘Included/Excluded’” when the Unit Rate is set to 0?', '如使用 BQ Excel，請在該項目輸入 0，當成功導入 BQ Excel後，請在網頁報價單的該項目選擇「包括」或「不包括」。', 'If you''re using BQ Excel, enter 0 for the item. After successfully importing the file, go to the corresponding item in the web quotation form and select either "Included" or "Excluded".', 'Lucas', NOW(), 'Lucas', NOW(), NULL),
('36', 'Tender', '投標標書', '為什麼在點擊「提交」後，系統會顯示錯誤訊息「請先回答聲明內容」？', 'Why does the system show the error message "Please answer the declaration first" after clicking "Submit"?', '請注意，提交標書前，必須先於網頁左下方完成法律聲明的回答。請選擇是否涉及任何法律訴訟，並儲存後再進行提交。', 'Before submitting, make sure to answer the legal declaration at the bottom left of the page. Select whether you''re involved in any legal proceedings, save, then submit.', 'Lucas', NOW(), 'Lucas', NOW(), NULL),
('37', 'Tender', '投標標書', '如何確認標書已成功提交？', 'How can I confirm that my tender has been successfully submitted?', '當成功回標，在標書列表最右的按鈕會更新為 「已回標」字眼，另外會收到一個系統電郵通知。如果按鈕顯示「已保存」，代表標書資料只暫存在網頁上，本公司在截標後不會收到。', 'Once the tender has been successfully submitted, the button on the far right of the tender list will update to show "Submitted". You will also receive a system-generated email notification. If the button shows "Saved", it means the tender data is only temporarily stored on the website and has not been officially submitted. In this case, the company will not receive your tender after the submission deadline.', 'Lucas', NOW(), 'Lucas', NOW(), NULL),
('38', 'Tender', '投標標書', '我可以怎樣修改接收標書通知的電郵地址？', 'How can I update the email address used to receive tender notifications?', '有關修改承判商註冊的電郵地址請聯絡標書負責人，只有該組別的標書負責人才有權限修改承判商註冊的電郵地址。', 'To update the registered email address of a contractor, please contact the tender coordinator. Only the designated tender coordinator for that group has the authority to make changes to the contractor’s registered email address.', 'Lucas', NOW(), 'Lucas', NOW(), NULL),
('39', 'Tender', '投標標書', '標書已提交後是否仍可更改或撤回？', 'Is it possible to make changes or withdraw a tender after submission?', '當成功回標後，只要在截標時間前，從標書列表按 「已回標」的按鈕進入填價單，把已上載的投標表格刪除後，標書就會解鎖供承判商修改報價單內容。只要修改後再次保存並列印投標表格，上載最新的投標表格後就可以再次提交標書。請注意截標時間，當撤回投標後，本公司就無法取得原本已回標的資料，請必須在截標時間前重新完成提交標書。', 'Once the tender has been successfully submitted, you can still make changes before the submission deadline. Simply go to the tender list, click the "Submitted" button, and delete the uploaded tender form. This will unlock the tender, allowing you to modify the quotation details. After making the necessary changes, save and print the updated tender form, then upload it again to resubmit the tender. Please note: once a tender is withdrawn, the original submitted data will no longer be accessible. Make sure to complete and resubmit the tender before the deadline.', 'Lucas', NOW(), 'Lucas', NOW(), NULL),
('40', 'Tender', '投標標書', '為什麼在點擊「列印投標表格」時，系統顯示「Material List Not saved」的錯誤訊息？', 'Why does the system show the error message "Material List Not saved" when I click "Print Tender Form"?', '如出現該信息提示代表你正在報購料組標書並且是從網頁報價單上直接輸入而不是使用BQ Excel 由於網頁需要在每一條材料單上載一張圖片，所以需要承判商在每一條材料單按一次保存。我們建議使用 BQ Excel 寫報價單及材料單會比較方便，而且該 Excel 是一個備份。萬一發生問題導致資料遺失，導入 BQ Excel 可以在 5 秒內補回報價單資料。如您在網頁上已輸入數據，你也可以先按「保存」。當保存後導出，BQ Excel 就可以取得網頁上的數據，無需你再次輸入。', 'If you see this message, it means you''re preparing a tender for a material group and entering data directly on the web quotation form instead of using BQ Excel. Since the web platform requires an image to be uploaded for each material item, contractors must click "Save" for each individual material entry. We recommend using BQ Excel to prepare both the quotation and material list—it’s more convenient and also serves as a backup. If any issue causes data loss, you can re-import the BQ Excel file and restore your quotation data in just 5 seconds. If you''ve already entered data on the web, you can click "Save" first. Once saved, exporting the BQ Excel file will capture the web data, so you won’t need to re-enter it manually.', 'Lucas', NOW(), 'Lucas', NOW(), NULL),
('41', 'Tender', '投標標書', '按「導入 BQ Excel」時出現「Import file accept .xlsx file only」，請問這是什麼原因？', 'When I click "Import BQ Excel," a message pops up saying "Import file accept .xlsx file only." What does this mean?', 'BQ Excel 主要的功能是把 Excel 的數據導入到網頁。如果本系統檢查到 Excel 內的資料不對應標書，系統將會阻止導入。您所上載的 Excel 檔案可能已被修改、選錯檔案，或標書已更新並重新出標。請返回報價單頁面，重新匯出最新版本的 BQ Excel，再進行填寫與匯入。', 'The main function of BQ Excel is to import data from Excel into the web platform. If the system detects that the data in the Excel file doesn''t match the tender, the import will be blocked. The file you uploaded may have been modified, may be the wrong file, or the tender may have been updated and reissued. Please return to the quotation page, export the latest version of the BQ Excel file, then fill it out and try importing again', 'Lucas', NOW(), 'Lucas', NOW(), NULL),
('42', 'Tender', '投標標書', '我未能在限時內完成標書準備，請問可否延後截標時間？', 'I wasn''t able to complete the tender preparation within the given timeframe. Would it be possible to request an extension of the submission deadline?', '有關延遲截標時間請聯絡標書負責人，只有該組別的標書負責人才有權限延遲截標時間。', 'Regarding any request to extend the tender submission deadline, please contact the designated tender officer. Only the officer responsible for that specific tender group has the authority to approve deadline extensions.', 'Lucas', NOW(), 'Lucas', NOW(), NULL),
('43', 'Tender', '投標標書', '為什麼在點擊「提交」時，系統顯示錯誤訊息：「列印投標表格後回標數據有更新，請重新下載列印投標表格再提交」？', 'Why does the system show the error message "The BQ has been updated. Please print the latest version of Form of Tender again" when I click Submit?', '本系統檢查到在列印投標表格後曾按過保存按鈕，本系統會當作標書有修改。請再次列印投標表格確保文件上的標書總價是最新的。', 'The system has detected that the "Save" button was clicked after printing the Form of Tender. This indicates that changes were made to the submission. Please reprint the Form of Tender to ensure the total tender price shown is up to date.', 'Lucas', NOW(), 'Lucas', NOW(), NULL);